//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace FigmaProject
{
	/// <summary>
	/// Represents a content item of type <see cref="Testimonial"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Testimonial : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "FigmaProject.Testimonial";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// logo.
		/// </summary>
		public ContentItemAsset logo { get; set; }


		/// <summary>
		/// Testimony.
		/// </summary>
		public string Testimony { get; set; }


		/// <summary>
		/// TestimonialName.
		/// </summary>
		public string TestimonialName { get; set; }


		/// <summary>
		/// TestimonialThumbnail.
		/// </summary>
		public ContentItemAsset TestimonialThumbnail { get; set; }


		/// <summary>
		/// TestimonialStars.
		/// </summary>
		public decimal TestimonialStars { get; set; }
	}
}