//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using CMS.OnlineForms.Types;

[assembly: RegisterBizForm(ContactUsFormItem.CLASS_NAME, typeof(ContactUsFormItem))]

namespace CMS.OnlineForms.Types
{
	/// <summary>
	/// Represents a content item of type ContactUsFormItem.
	/// </summary>
	public partial class ContactUsFormItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.ContactUsForm";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactUsFormItem fields.
		/// </summary>
		private readonly ContactUsFormItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get => ValidationHelper.GetString(GetValue(nameof(Name)), @"");
			set => SetValue(nameof(Name), value);
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string Email
		{
			get => ValidationHelper.GetString(GetValue(nameof(Email)), @"");
			set => SetValue(nameof(Email), value);
		}


		/// <summary>
		/// BusinessPhone.
		/// </summary>
		[DatabaseField]
		public string BusinessPhone
		{
			get => ValidationHelper.GetString(GetValue(nameof(BusinessPhone)), @"");
			set => SetValue(nameof(BusinessPhone), value);
		}


		/// <summary>
		/// LeaveAMessage.
		/// </summary>
		[DatabaseField]
		public string LeaveAMessage
		{
			get => ValidationHelper.GetString(GetValue(nameof(LeaveAMessage)), @"");
			set => SetValue(nameof(LeaveAMessage), value);
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactUsFormItem fields.
		/// </summary>
		[RegisterProperty]
		public ContactUsFormItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with ContactUsFormItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactUsFormItemFields : AbstractHierarchicalObject<ContactUsFormItemFields>
		{
			/// <summary>
			/// The content item of type ContactUsFormItem that is a target of the extended API.
			/// </summary>
			private readonly ContactUsFormItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactUsFormItemFields" /> class with the specified content item of type ContactUsFormItem.
			/// </summary>
			/// <param name="instance">The content item of type ContactUsFormItem that is a target of the extended API.</param>
			public ContactUsFormItemFields(ContactUsFormItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get => mInstance.Name;
				set => mInstance.Name = value;
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get => mInstance.Email;
				set => mInstance.Email = value;
			}


			/// <summary>
			/// BusinessPhone.
			/// </summary>
			public string BusinessPhone
			{
				get => mInstance.BusinessPhone;
				set => mInstance.BusinessPhone = value;
			}


			/// <summary>
			/// LeaveAMessage.
			/// </summary>
			public string LeaveAMessage
			{
				get => mInstance.LeaveAMessage;
				set => mInstance.LeaveAMessage = value;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactUsFormItem" /> class.
		/// </summary>
		public ContactUsFormItem() : base(CLASS_NAME)
		{
			mFields = new ContactUsFormItemFields(this);
		}

		#endregion
	}
}