//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace FigmaProject
{
	/// <summary>
	/// Represents a page of type <see cref="Blogs"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Blogs : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "FigmaProject.Blogs";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// BlogPicture.
		/// </summary>
		public IEnumerable<FinalProject.Assets> BlogPicture { get; set; }


		/// <summary>
		/// BlogDateCreated.
		/// </summary>
		public DateTime BlogDateCreated { get; set; }


		/// <summary>
		/// BlogTitle.
		/// </summary>
		public string BlogTitle { get; set; }


		/// <summary>
		/// BlogContent.
		/// </summary>
		public string BlogContent { get; set; }


		/// <summary>
		/// BlogCategory.
		/// </summary>
		public IEnumerable<TagReference> BlogCategory { get; set; }
	}
}