//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace FinalProject
{
	/// <summary>
	/// Represents a page of type <see cref="ArticlesDetail"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class ArticlesDetail : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "FinalProject.ArticlesDetail";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// ArticleTitle.
		/// </summary>
		public string ArticleTitle { get; set; }


		/// <summary>
		/// ArticleContent.
		/// </summary>
		public string ArticleContent { get; set; }


		/// <summary>
		/// ArticleDateCreated.
		/// </summary>
		public DateTime ArticleDateCreated { get; set; }


		/// <summary>
		/// ArticleThumbnail.
		/// </summary>
		public IEnumerable<Assets> ArticleThumbnail { get; set; }
	}
}