//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace FinalProject
{
	/// <summary>
	/// Represents a page of type <see cref="ServicesDetail"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class ServicesDetail : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "FinalProject.ServicesDetail";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// ServicesTitle.
		/// </summary>
		public string ServicesTitle { get; set; }


		/// <summary>
		/// ServicesContent.
		/// </summary>
		public string ServicesContent { get; set; }


		/// <summary>
		/// ServicesDateCreated.
		/// </summary>
		public DateTime ServicesDateCreated { get; set; }


		/// <summary>
		/// ServicesThumbnail.
		/// </summary>
		public IEnumerable<Assets> ServicesThumbnail { get; set; }
	}
}